### ISSUE TITLE
TPM2 on ASRock's H97M Pro4 Motherboard

### ISSUE THREAD

**Issue by QasimK** [QasimK/qasimk.github.io#1]
This issue is for comments on the blog post [TPM2 on ASRock H97M Pro4 Motherboard](http://qasimk.io/2018/ASRock-Pro4-TPM2/).

**Comment by razvanu** [comment]
will this item work? https://www.ebay.com/itm/ASRock-TPM2-S-Module-V2-0/382191036061
with the new bios, V2.1c - https://mega.nz/#!k1IChbrS!hPs4FcRD441qG0imGsG2r8oYccktyc75yS1XwN5f4D4

**Comment by QasimK** [comment]
@razvanu I can't really say. It is labelled as "ASRock TPM2-S Module", and the module that I got was also labelled as "TPM2-S". It sounds like it would work. It's probably worth getting it and returning it if it doesn't work :smiley:
