### ISSUE TITLE
Setting up Radicale on a Raspberry Pi

### ISSUE THREAD

**Issue by QasimK** [QasimK/qasimk.github.io#3]
Comment on [Setting up Radicale on a Raspberry Pi](http://qasimk.io/2017/radicale-server/).

**Comment by yaw89** [comment]
To use bcrypt with a raspbian-packaged radicale, you need the following packages:

    sudo apt-get install build-essential libssl-dev libffi-dev python-dev
    sudo python -m pip install –upgrade passlib
    sudo python -m pip install –upgrade bcrypt

**Comment by QasimK** [comment]
Hi @yaw89, thanks for your suggestion. I will give installing the dependencies a go and update the article if it works out
